pipeline {
    agent any

    environment {
        AWS_CREDS = credentials('srini-aws-personal')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/your-repo/sample-app.git'
            }
        }

        stage('Terraform') {
            steps {
                dir('app_deploy_terraform/terraform') {
                    sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_CREDS_USR
                        export AWS_SECRET_ACCESS_KEY=$AWS_CREDS_PSW

                        terraform init
                        terraform plan
                        terraform apply -auto-approve
                    '''
                }
            }
        }

    }
}
